### ISSUE TITLE
add-link issue

### ISSUE THREAD

**Issue by whyrusleeping** [dignifiedquire/randor#17]
looks like somethings not quite right with the add link code:

```
Unhandled rejection Error: incorrectly formatted root hash: add-link
    at /home/whyrusleeping/code/randor/node_modules/ipfs-api/src/request-api.js:31:21
    at finish (/home/whyrusleeping/code/randor/node_modules/wreck/lib/index.js:146:20)
    at wrapped (/home/whyrusleeping/code/randor/node_modules/hoek/lib/index.js:867:20)
    at ClientRequest.onResponse (/home/whyrusleeping/code/randor/node_modules/wreck/lib/index.js:169:20)
    at ClientRequest.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:458:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at Socket.socketOnData (_http_client.js:348:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)
```

**Comment by dignifiedquire** [comment]
Can't reproduce
